### ISSUE TITLE
Sling Loading Helmet/Facemask

### ISSUE THREAD

**Issue by Qaiten** [2bnb/2bnb-extras#10]
**Arma 3 Version:** `1.88` (stable / rc / dev)
**2BNB Extras Version:** `1.1.0` (stable / dev + commit hash)
**2BNB Modpack Version:** `1.0.4a`

**Description:**
- After a detailed discussion between Arend, Plank and I before the Operation tonight, we briefly discussed the want/need to have gas masks as sling loadable to our uniforms (like backpacks in a fashion). 

- What we need:
1 - Gas masks to be sling loadable
2 - Gas Masks to count as facemasks when sling loading (Because if they're helmets, you gon' get 1 shot like a bitch).

**Steps to reproduce:**
- Make Face masks sling loadable to body.
- Make Gas Masks part of this.

**Where did the issue occur?**
- 2BNB Server - Arsenal

**Comment by UrekD** [comment]
> Because if they're helmets, you gon' get 1 shot like a bitch.
Not true sometimes :P 
I have modified [this](https://steamcommunity.com/sharedfiles/filedetails/?id=1354112941&searchtext=sling), if permission is given or the author uploads a version for gasmaks we will be able to use that simply. Up to Plank if he manages to get permission.

**Comment by Saborknight** [comment]
Done in 9d75d11118bf49dd01ab60913df7e1fd21648d51
