### ISSUE TITLE
Implement the ladder tweak method

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#100]
The ladder tweak method:
![image](https://user-images.githubusercontent.com/9272259/73731638-f0d97c80-478c-11ea-80c8-ec4e60cf423a.png)

But how fast shall we make it, is the question! Make the multiplier a CBA Setting.

**Comment by UrekD** [comment]
I want my god damn space program! 2x

**Comment by Saborknight** [comment]
Done in the below commit
