### ISSUE TITLE
Default kit update/improvements

### ISSUE THREAD

**Issue by spraka** [2bnb/2bnb-extras#104]
**Arma 3 Version:** `1.xx` (stable / rc / dev)
**2BNB Extras Version:** `1.x.x` (stable / dev + commit hash)
**2BNB Modpack Version:** `1.x.x`

**Description:**
general weight and accuracy improvements

**Steps to reproduce:**
just open the arsenal

**list of kits**
[revised arma kits.txt](https://github.com/2bnb/2bnb-extras/files/4280632/revised.arma.kits.txt)

**Comment by Saborknight** [comment]
Dependency: v2.6.2 of the modpack to be released on the 15th of March.

**Comment by Saborknight** [comment]
I've tweaked the kits slightly, and made their camouflage variants. Just waiting on a review with @Qaiten to make sure they're all good.

**Comment by Saborknight** [comment]
b75b266

**Comment by Saborknight** [comment]
Done in the below commit
