### ISSUE TITLE
Custom Patches - Add "Recon Wolves" patch

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#118]
Patch submitted by Aeilmar, it's his Company's badge.
![image](https://user-images.githubusercontent.com/9272259/77803586-93e5ad00-70d1-11ea-9c64-b5068e8d7ad4.png)

**Comment by Saborknight** [comment]
Might have to get rid of the white crap in between the colours

**Comment by Kriegyeet** [comment]
Done in the above commit
