### ISSUE TITLE
Gas Mask still viewable when slung on invisible Zeus

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#12]
**Arma 3 Version:** `1.88` (stable / rc / dev)
**2BNB Extras Version:** `1.2.1` (stable / dev + commit hash)
**2BNB Modpack Version:** `1.0.4b`

**Description:**
- Mask is viewable when Slung by a Zeus player who has made himself invisible.

**Steps to reproduce:**
- Sling mask
- Make yourself invisble through Zeus
- Watch a floating mask move about as you do

**Where did the issue occur?**
- 2BNB Server

**Comment by UrekD** [comment]
Wrong reference on commit. I presume it's the same for the helmet?

**Comment by Saborknight** [comment]
I guess so. Haven't checked yet. It's not too big of a deal. If Sling Helmet also has this happening then we can safely ignore, because if it's fixed on Sling Helmet then theoretically it would fix itself for Sling Mask.

**Comment by Saborknight** [comment]
Same happens with the helmets. Ignore
