### ISSUE TITLE
New Sounds NIArms HK416

### ISSUE THREAD

**Issue by Qaiten** [2bnb/2bnb-extras#124]
**Arma 3 Version:** `1.xx` (stable / rc / dev)
**2BNB Extras Version:** `1.x.x` (stable / dev + commit hash)
**2BNB Modpack Version:** `1.x.x`

**Description:**
The new NIArms HK416 - needs to have a soundfile from [Tarkov Weapon Sounds JSRS Ver.] implemented to them.

**Steps to reproduce:**
- Replace sound file attached to the weapon.

**Where did the issue occur?**
- N/A

**Screenshots/Video:**
- Current NIArms sounds: [Current In-Game NIArms Sounds](https://www.youtube.com/watch?v=jdgEM30o1F4&).
- Wanted Tarkov Weapon sounds: [Tarkov Weapon Sounds](https://www.youtube.com/watch?v=p52kfEyeS38&).

**Comment by Saborknight** [comment]
Done in the below commit
