### ISSUE TITLE
Carbomb IEDs can be defused only by EODs 

### ISSUE THREAD

**Issue by aeilmar** [2bnb/2bnb-extras#135]
Currently everyone can do that, should be only people who have Engineer trait

**Comment by Qaiten** [comment]
It was made that way because there was an issue with people being made into an Engineer as Zeus on maps where EOD was thrown in last minute since most maps don't have an assigned role. 

People need a defusal kit anyway, and shouldn't have one unless they are an EOD.

We should test it the next chance we get.

**Comment by aeilmar** [comment]
Afaik it doesnt require defusal kits, nor toolkits. You can ACE interact with the vehicle regardless of the role or equipment you have on you.

**Comment by Qaiten** [comment]
> 
> 
> Afaik it doesnt require defusal kits, nor toolkits. You can ACE interact with the vehicle regardless of the role or equipment you have on you.

Is it only the carbomb IEDs that this is an issue with?

**Comment by Saborknight** [comment]
So, the interactions themselves were made by the original author of [Fox] Suicide Bomber. They never included any checks related to Engineer/EOD skills nor the possession of any defusal kit or toolkit.

So, those checks will need to be added to https://github.com/2bnb/2bnb-extras/blob/master/addons/suicide_bomber/config.cpp#L47.

Actually, I need to see what the `canDisarmIED` function actually checks... Up until now I thought it only checked if the vehicle had been "Examined", nothing else... But now I can't remember

**Comment by Saborknight** [comment]
Done in the last commit
