### ISSUE TITLE
2x New Custom Patch Please

### ISSUE THREAD

**Issue by Amateur-God** [2bnb/2bnb-extras#147]
![Carmichael Patch](https://user-images.githubusercontent.com/68581288/88017966-aa9b8e00-cb1e-11ea-93c5-64c1a56b636b.png)
![Carmichael Patch 2](https://user-images.githubusercontent.com/68581288/88017970-ab342480-cb1e-11ea-91b7-e385c978d41d.png)

**Comment by Saborknight** [comment]
Done in the below commit
