### ISSUE TITLE
Norwegian Task Force Vehicles

### ISSUE THREAD

**Issue by xZaniity** [2bnb/2bnb-extras#151]
Size : 264MB
Features: CV90N, IVECO M2, IVECO RWS, Bell Helicopter, Scania Transport Truck, NH90 Transport Helicopter and M113s retextured to Norwegian vehicles.

https://github.com/Tittoffer/NorwegianTaskForce
https://docs.google.com/spreadsheets/d/14DxzWqjp9WlpRB9yDjJroXFIcGJJzaiV6ghzJZemIDM/edit#gid=0

**Comment by Saborknight** [comment]
### Reference images
M113:
https://upload.wikimedia.org/wikipedia/commons/f/f1/Norwegian_army_M113_w_mine_rollers_at_Kandahar.jpg
https://cdn.discordapp.com/attachments/737185956049846273/742228501649817671/unknown.png
https://cdn.discordapp.com/attachments/737185956049846273/742228433471537192/unknown.png
https://www.aldrimer.no/wp-content/uploads/2015/08/osh_nj15-7.jpg
https://cdn.discordapp.com/attachments/737185956049846273/742228568129536090/unknown.png

CV90:
https://cdn.discordapp.com/attachments/545649832249786390/742903156283015238/unknown.png
https://cdn.discordapp.com/attachments/545649832249786390/742904934520848504/unknown.png
https://cdn.discordapp.com/attachments/737185956049846273/742897789092233236/unknown.png
https://cdn.discordapp.com/attachments/737185956049846273/742897645537984555/unknown.png

Iveco:
https://i.imgur.com/beGFmbE.jpg

Scania:
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0cy1SkfWg6mH5ls66KnXqgXWMTKfLbdUjSA&usqp=CAU
https://i.ytimg.com/vi/IKkvGR-DbZk/maxresdefault.jpg
https://www.retrade.eu/i/product_img/5488-0.jpg/detail/Scania_P-93_MK_4x4.jpg
https://kommunikasjon.ntb.no/data/images/00198/f776b24b-849c-4dec-bb93-bb308f9e0fef-w_960.JPG

Bell 412:
https://nordnorskdebatt.no/sites/default/files/styles/1000/public/main/articles/forsvaret_heli.jpg?itok=7SSFO-p1
https://www.sagat.no/bilder/web/badaba562b569d6cd2aae2e0fe.jpg?v=1588363529
https://g.acdn.no/obscura/API/dynamic/r1/ece5/tr_1080_720_l_f/0000/avno/2019/11/13/20/7PL0biY1Rpg.jpg?chk=2A27FA
https://www.strategicfront.org/forums/proxy.php?image=https%3A%2F%2Fmediearkiv.forsvaret.no%2Ffotoweb%2Fcache%2F5000%2FIndekserte%2520bilder1%2F20120615th_001.t508e45a8.m1200.xFJVA00xA.jpg&hash=398a69bb27d7eadd6e29d82bcf2cc830
https://www.strategicfront.org/forums/proxy.php?image=https%3A%2F%2Fmediearkiv.forsvaret.no%2Ffotoweb%2Fcache%2F5000%2FIndekserte%2520bilder1%2F2019%2F06%2F20190603tk_I8949.t5cf56e65.m800.xPlfsBpcG.jpg&hash=9ee8657aee1608112a62308f5b0344ae
https://www.strategicfront.org/forums/proxy.php?image=https%3A%2F%2Fmediearkiv.forsvaret.no%2Ffotoweb%2Fcache%2F5000%2FIndekserte%2520bilder1%2F2019%2F06%2F20190603tk_I9112.t5cf56e86.m800.xnGfTyiHs.jpg&hash=e05ba135daa2283677080c3b2e406be8
https://www.strategicfront.org/forums/proxy.php?image=https%3A%2F%2Fmediearkiv.forsvaret.no%2Ffotoweb%2Fcache%2F5000%2FIndekserte%2520bilder1%2F2019%2F06%2F20190603tk_I9148.t5cf56e8c.m800.xCe864Sys.jpg&hash=b948c8b5feb1e8038f77aa36cc14cd2a
https://www.strategicfront.org/forums/proxy.php?image=https%3A%2F%2Fmediearkiv.forsvaret.no%2Ffotoweb%2Fcache%2F5000%2FIndekserte%2520bilder1%2F2019%2F06%2F20190603tk_I9470.t5cf56eb4.m800.xWoLEZW8S.jpg&hash=8289bef20bf46752c7d0e21089f0109b

**Comment by Saborknight** [comment]
Done in the below commit, however the Iveco was not included due to the mod it depended on being discontinued and broken.
