### ISSUE TITLE
Replace M2 Browning (all preferably) sounds with the "M2 HMG .50"

### ISSUE THREAD

**Issue by Qaiten** [2bnb/2bnb-extras#154]
**Description:**
Aeilmar and I tested a few vehicles for sounds to "beef up" the M2 from what it currently is - just an unremarkable sound while other games like Squad have great sounds for it. It sounds deadly and you can hear it on the battlefield too.

**Steps to reproduce:**
- Replace sound files that link the M2 from RHS to the M2 HMG .50 sound.

**Where did the sound occur?**
- FIA Faction > Turret > M2 HMG .50

**Comment by Saborknight** [comment]
Classname: `I_G_HMG_02_high_F`

**Comment by Saborknight** [comment]
RHS is no longer included, this is no longer necessary
