### ISSUE TITLE
Add new roles to the Norwegian Army faction

### ISSUE THREAD

**Issue by Kriegyeet** [2bnb/2bnb-extras#157]
With the Sniper qualification becoming a thing and allowing those roles in missions, it'd be great to have these roles in the faction roster in Eden and Zeus, so mission makers don't have to do so themselves.

Roles to implement per camo:
---
- [x] Recon IC
- [x] Recon Rifleman
- [x] Sniper
- [x] Spotter

**Comment by Saborknight** [comment]
@aeilmar or @qaiten could either of you send me loadouts for sniper and spotter please?

**Comment by Saborknight** [comment]
[recon_sniper_spotter_loadouts.txt](https://github.com/2bnb/2bnb-extras/files/5025484/recon_sniper_spotter_loadouts.txt)

Aeilmar sent me this in DMs.

He had also asked me to do Recon units in the faction, but I had forgotten, and so did he, so I'll add that in to this issue.

**Comment by Saborknight** [comment]
Done in the below commit
