### ISSUE TITLE
JSHK Contamination Area Mod - Investigate "Environment" settings module

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#17]
Need to check the enviroment module and possibly add that to settings if it's any good

_Originally posted by @GhostTheSlayer in https://github.com/Saborknight/2bnb-extras/issues/3#issuecomment-466574153_

---

Investigate the "Environmental Effects Setting" module and see what it does. The 3DEN module does not contain any editable settings... it is currently just a module you can place down and that's it.

Thus, to find out what it does and whether or not these "Effects" may be worth keeping/implementing, read the code and report the findings here.

If considered worth it, implement into settings or as a Zeus module, whichever is more appropriate.

**Comment by UrekD** [comment]
The module was initialized itself anyway, it's rain on mask for ex. Author will be implementing setting n shit .../he's working on it.
