### ISSUE TITLE
ADD: the Hex  Alt+Tab = Boom patch sendt to Carmichael

### ISSUE THREAD

**Issue by Hex9909** [2bnb/2bnb-extras#187]
**Arma 3 Version:** `1.xx` (stable / rc / dev)
**2BNB Extras Version:** `1.x.x` (stable / dev + commit hash)
**2BNB Modpack Version:** `1.x.x`

**Description:**
Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- 2BNB Server / Zeus / 3DEN Editor / Virtual Arsenal

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file.

**Screenshots/Video:**
- Put cursor here and drag/drop image, or put a link to a [youtube](https://youtube.com) video here.

**Comment by Amateur-God** [comment]
Added in latest 2bnb Essentials update
