### ISSUE TITLE
Detect & delete any extra PBOs in the addons folder already existing

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#20]
Modify the `make.ps1` file to do the above.

**Comment by UrekD** [comment]
My suggestion making it so everytime the build script is ran it deleted the previous build. While rebuilding without clearning it multiple times gear.pbo was like 36mb all tho its only like 3 in reality now

**Comment by Saborknight** [comment]
Done with the above mentioned commits.
