### ISSUE TITLE
Ambient voices

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#23]
There may already be a mod for this, but I feel like there's a like of ambient sounds when it comes to voices.

For instance, civilians walking around, sometimes they should be talking, or at least sounds like they're talking, either to each other or to themselves. This should depend on their awareness states, so different types of ambient speech should be coming from characters depending on whether or not they are set to careless, aware, cautious, alert or silent.

Military voices should, again, be different from civilians. More gruff, more concise, and stronger. There would also be a difference depending on sides, or maybe even being as detailed as different nationalities having different voices.

Vanilla Arma 3 already has speech for different nationalities, etc. So we could use those. My issue is that there should be little silence in situations where multiple characters are in the same vicinity. At least there should be a hum of voices, if not clearly heard speech.

We should research speech mods first...

**Comment by Saborknight** [comment]
See civilian ambient voices in C&C: Generals

**Comment by UrekD** [comment]
ALIVE civ population is working on ambient sound, worth taking a look when time gives https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.10.1.1905201

**Comment by UrekD** [comment]
Has radio sounds, dogs, car alarms for civ housing didnt see civs speak themself. They stoned me even I belive, they gather and form crowds now aswell! Also civs scream and flee now..

**Comment by Saborknight** [comment]
Duplicate of #30 . I think we can leave it all up to ALiVE for the ALiVE missions. However, giving a Zeus the ability to place these things down live would be awesome. So, I'm closing this issue since we can use ALiVE, and I'll keep #30 open on the premise that we add in Zeus modules to allow for area based atmospheric spawning.
