### ISSUE TITLE
Vests with interchangeable name tags

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#25]
Make the current vest or just in general vests where we can easily put in a name tag of a person on, or any piece of clothing we could use for that. Here you have an example of a cap, it's the same principle need to make a hidden selection for the tag some how , I have no clue how tho.

http://www.mediafire.com/file/b41jeybs8dq0g8o/cap+with+patch.zip

**Comment by Saborknight** [comment]
Reference for information and instructions: https://forums.bohemia.net/forums/topic/156727-cap-with-interchangeable-flag-patch/

**Comment by UrekD** [comment]
So few problems I downloaded blender and ...
1. The issue with permission to debin and then edit the model
2. Fucking blender is weird AF
3. Need to learn to bin and what not

Otherwise yeah it's just a defined area..

**Comment by UrekD** [comment]
@Saborknight  need fonts for patch.

**Comment by UrekD** [comment]
So it seems that the texture for vest is multiple things packet into it so removing it takes some times, I got it around 900kb per vest, (4MB per person for all 4 variants). Can most likely be cut down more.

Current problems:
-belt and items on it are black
- Items in pocket are blacket a bit or fully


[gear.zip](https://github.com/Saborknight/2bnb-extras/files/3270145/gear.zip)
![20190610015809_1](https://user-images.githubusercontent.com/38784343/59165980-e397bf80-8b23-11e9-86cc-3a2be31c4d4d.jpg)
