### ISSUE TITLE
Make Sucicide Bombers (ACE, Achilles & ALiVE) speak instead of message

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#26]
Instead of a suicide bomber sending a global message in text before blowing up, make them actually play a sound file from their person, hearable clearly from at least 30m, maybe more (Testing required).

**Comment by UrekD** [comment]
There are 2 functions other one doesn't send the message, not sure about sound. But idealy the function should automatically give the bomber the vest declared that they will be wearing 

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Saborknight** [comment]
Well, the vest does appear and work fine. I don't know what you mean by function... you mean the different mod Zeus modules (Achilles / ACE)?

**Comment by UrekD** [comment]
It adds the vest itself?

**Comment by Saborknight** [comment]
Achilles does, I know that. Haven't check ACE yet. As for ALiVE, not sure.

**Comment by UrekD** [comment]
Wasn't aware of that.

**Comment by UrekD** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1373303221

**Comment by Saborknight** [comment]
That's perfect, could we please have it added for the next modpack update @GhostTheSlayer @Qaiten ?

**Comment by Saborknight** [comment]
We may be adding the above mentioned mod to the modpack, hopefully. On hold until this is confirmed. If confirmed, then this issue should be closed

**Comment by Saborknight** [comment]
This mod was added a while ago, so this is done
