### ISSUE TITLE
JSHK Contamination Area Mod - Zeus modules

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#3]
**Arma 3 Version:** `1.88` (stable)
**2BNB Framework Version:** `1.0.3` (stable)
**2BNB Modpack Version:** `1.0.4a`

**Description:**
- Can't define Contaminated areas, since author didn't add it or is unable to. Someone needs to look into it... and make em if possible yay .. :D

**Where did the issue occur?**
- Zeus

**Comment by UrekD** [comment]
Would need to make a input dialog to get the values needed and then modify the script to use those from the dialog once the module was placed in zeus, most likely would need to make 2 seperate modules 1 for eden and 1 for zeus. The author gave up on this I belive 2 y ago... 
[This was listed to look at as examples but most of the dialog is ofset, achillies is another thing not sure what would be best](https://forums.bohemia.net/forums/topic/166253-curator-presets-mod/)

**Comment by UrekD** [comment]
Making modules with Achillies, you can take a look at Fetzen's tool kit he got em to work somehow

**Comment by Saborknight** [comment]
I've successfully implemented the Zeus module. It should kind of work (untested), however there are a few settings missing that would normally be applied through 3DEN modules. We need to either hardcode or create CBA settings for them instead.

@GhostTheSlayer mind taking over? I need sleep and was hoping for this to be completed before next op.

**Comment by UrekD** [comment]
Fixed a typo. 6fd3d8524a42b3f857f447e90dbd00095d64f9c5. 
I'm so lost current error:
![image](https://user-images.githubusercontent.com/38784343/53050835-899ebb80-349a-11e9-8b12-7b95244e6a31.png)
Pretty sure next if has a error aswell.

**Comment by Saborknight** [comment]
Yep, that isn't a typo, that's a big oopso. I've solved that problem using a helper function called `toBoolean`, which basically turns any number, whether it be a `STRING` or `SCALAR` typeName, into a `BOOL`.

**Comment by UrekD** [comment]
Current bugs:

Zeus module:
-Entire map dosen't work
-On object dosen't work [PICTURE](https://cdn.discordapp.com/attachments/488445797566906372/548632861842997258/unknown.png)

Extra:
-Maybe add safezone in case off whole map
-Need to check the enviroment module and possibly add that to settings if it's any good

**Comment by Saborknight** [comment]
Hmm. Weird. `_pos` is supposed to be an array...

In general, most of the errors we'll be encountering here will have all to do with types of the data we're passing the functions. So, we should be double checking the `typeName` of the data before passing. Only for debug purposes though.

I'm not sure why the world contamination doesn't work, the cause of that will be interesting.

As to the safe zone, good call. Will implement.

And the environment module.... I have no idea what it does. It has no settings related to it, so need to check and see what the code does.

**Comment by Saborknight** [comment]
We should probably handle the setting when it is changed, using the [setting changed script `_script`](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#setting-changed-script-_script).

**Comment by Saborknight** [comment]
So it turns out that "Entire Map" doesn't work with the 3DEN module either... So we'll leave that be for now.

**Comment by Saborknight** [comment]
Use:
https://github.com/ArmaAchilles/Achilles/blob/master/%40AresModAchillesExpansion/addons/modules_f_achilles/Spawn/functions/fn_SpawnEffect.sqf
and
https://github.com/ArmaAchilles/Achilles/wiki/Custom-Modules

for references. I'm putting this issue on hold, the above is research material I had open until now.

**Comment by Saborknight** [comment]
In reference to the issue I was having where the Zeus Module was not editable after placing it down:
https://community.bistudio.com/wiki/addCuratorEditableObjects

**Comment by UrekD** [comment]
Original author has returned and is working on it/already made it.
