### ISSUE TITLE
Zeus Module - Make vehicle suicide bomber

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#35]
So, we have a unit suicide bomber module by achilles, and it is possible to make a vehicle an IED. However, there are no visual indications on the vehicle that is may be explosive. 

So, let's create a module that attaches an explosive charge, satchel or other onto the dashboard or inside seat of the vehicle so that there is a visual indication of an explosive there.

#### Why not attach to the outside of the vehicle?
Because that is too unrealistically obvious.

For now I am able to do it manually via Zeus with the following process:
1. Place vehicle and explosive, and move the explosive to the desired location on the vehicle
1. Use the "Attach To" Achilles module to anchor the explosive to the vehicle
1. Use the "Create IED" Achilles module, using the settings
    a. Activation Mode: Radio - this means speed of the target unit does not matter, which is important if the vehicle is moving but the target not

But it would be great if this process could be made much easier.

**Comment by GhostTheSlayer** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1373303221

**Comment by Saborknight** [comment]
Vehicles to be used:
```sqf
"UK3CB_C_Datsun_Closed",
"UK3CB_C_Datsun_Open",
"C_Van_01_fuel_F",
"UK3CB_C_Hatchback",
"C_Hatchback_01_F",
"C_Hatchback_01_sport_F",
"UK3CB_C_Hilux_Closed",
"UK3CB_C_Hilux_Open",
"C_Kart_01_F",
"C_Offroad_02_unarmed_F",
"UK3CB_C_Lada",
"UK3CB_C_LandRover_Open",
"UK3CB_C_LandRover_Closed",
"UK3CB_Civ_LandRover_Hard_Blue_A",
"UK3CB_Civ_LandRover_Soft_Blue_A",
"C_Offroad_01_F",
"C_Offroad_01_comms_F",
"C_Offroad_01_repair_F",
"C_Quadbike_01_F",
"UK3CB_C_Sedan",
"UK3CB_C_Skoda",
"UK3CB_C_S1203",
"UK3CB_C_S1203_Ambulance",
"C_SUV_01_F",
"C_Tractor_01_F",
"C_Van_01_transport_F",
"C_Van_01_box_F",
"UK3CB_C_UAZ_Closed",
"UK3CB_C_UAZ_Open",
"C_Van_02_transport_F",
"UK3CB_C_Gaz24",
"UK3CB_C_Golf",
"C_UAV_06_F"
```
Explosives to be used:
```sqf
"ModuleExplosive_SatchelCharge_F",
"ModuleExplosive_Claymore_F",
"ModuleExplosive_DemoCharge_F"
```

## Research so far
HitPart eventhandler code: https://forums.bohemia.net/forums/topic/155616-vehicle-parts-name/
Selection points dump: https://forums.bohemia.net/forums/topic/166473-selectionsmemory-points-dump/
Use `createVehicleCrew` to spawn driver in the vehicle, when the vehicle has been spawned using `createVehicle`.

**Comment by Saborknight** [comment]
We now use Fox's Suicide Bomber mod. However, that mod doesn't actually implement a visible explosive. This may be an idea to do at some point. However, for now, this is done and works fine.
