### ISSUE TITLE
Custom Units

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#4]
**Arma 3 Version:** `1.88` (stable)
**2BNB Framework Version:** `1.0.3` (stable)
**2BNB Modpack Version:** `1.0.4a`

**Description:**
Ford's custom units:
- [x] Norwegian faction
- [x] Terrarist group
- [ ] ~Suicide civs~
- [ ] ~Enemy's with CBRN gear/gas masks~

**Comment by Saborknight** [comment]
The other two units done or?

**Comment by UrekD** [comment]
CBRN currently not needed will most likely see if forcinf gasmasks could be a better alternative than just a copy of unit for a gas mask, or maybe via  the same thing as include crew works. (Will look back when needed)

Suicide bomber should be given a vest by the function would be the best way. 



_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by UrekD** [comment]
Suicide civs not needed since function adds vest, other on hold cancelled/ on hold since not needed, thinking about just making a function which force equips masks for deployed group via zeus

**Comment by Saborknight** [comment]
Similar to the "Flashlights on/off" module from Achilles? Good idea.
