### ISSUE TITLE
Gear loss on Survivable crash

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#42]
Make it so when you crash and survive, that there is a chance of gear loss:
- Losing items from containers (vest,bag,uniform)
- Losing full item (weapon, radio, gps, vest,bag...)

**Comment by Saborknight** [comment]
Add to this, the chance to find random gear from the contents of the helicopter strewn around the immediate area of the crash. Not all, only some items. 

- Throwing around some items from inside the vehicle
- Throwing around some items from inside containers of players
- Throwing around some full items

**Comment by UrekD** [comment]
Shouldn't we close this?

**Comment by Saborknight** [comment]
Yep, definitely. My bad.
