### ISSUE TITLE
Add Music playlist to play in vehicles

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#43]
On ACE interact when in a vehicle, add an option to turn on radio and play music from our convoy playlist!
Volume should be set in CBA settings and should be client side only.
Songs should be synchronised between vehicles.
Song order and the song that starts off should all be random

Maybe allow people to choose a song?

### Features "KLPQ Music Radio" implements right now
- [x] ACE Interact to turn on/off for the single vehicle
- [x] Music syncronised between all vehicles with music playing
- [x] ACE Interact option to play on outside speakers
- [x] CBA Setting for a client to turn the volume down
- [x] CBA Setting for a client to enable this (Default: enabled)

**Comment by Saborknight** [comment]
We have a direct contender! Lets see if he'll allow us to extend his mod rather than us working from scratch. It already has features 1,2,4, and 6 implemented!

Steam Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=1241545493
Github: https://github.com/rebelvg/klpq_musicRadio

**Comment by boyanpapazchev** [comment]
Bochka, Bass, Kolbaser [XS Project] - https://www.youtube.com/watch?v=VLW1ieY4Izw
ТРИ ПОЛОСКИ / THREE STRIPES - https://www.youtube.com/watch?v=QiFBgtgUtfw
Ez Katka [DJ Blyatman & Russian Village Boys] - https://www.youtube.com/watch?v=J3k54wDsjP4
Deja Vu [Initial D] - https://www.youtube.com/watch?v=dv13gl0a-FA
Crab Rave [Noisestorm] - https://www.youtube.com/watch?v=LDU_Txk06tM
Africa [Toto] - https://www.youtube.com/watch?v=FTQbiNvZqaY
Pumped up Kicks [Foster The People] - https://www.youtube.com/watch?v=SDTZ7iX4vTQ
Fichtl's Lied [Die Woodys] - https://www.youtube.com/watch?v=dP9Wp6QVbsk
7th Element [Vitas] - https://www.youtube.com/watch?v=IwzUs1IMdyQ
Sandstorm [Darude] - https://www.youtube.com/watch?v=y6120QOlsfU
Never Gonna Give You Up [Rick Astley] - https://www.youtube.com/watch?v=dQw4w9WgXcQ
Take On Me [a-ha] - https://www.youtube.com/watch?v=djV11Xbc914
Move Bitch [Ludacris] - https://www.youtube.com/watch?v=3oIbztWsY8g
All Star [Smash Mouth] - https://www.youtube.com/watch?v=5ZYgIrqELFw
Tokyo Drift [Teriyaki Boyz] - https://www.youtube.com/watch?v=iuJDhFRDx9M
Tunak Tunak [Daler Mehndi] - https://www.youtube.com/watch?v=vTIIMJ9tUc8
Fortunate Son [Creedence Clearwater Revival] - https://www.youtube.com/watch?v=ZWijx_AgPiA
The House of the Rising Sun [The Animals] - https://www.youtube.com/watch?v=0sB3Fjw3Uvc
Riders On The Storm [The Doors] - https://www.youtube.com/watch?v=iv8GW1GaoIc
All Right Now [Free] - https://www.youtube.com/watch?v=WTfCSRFb0zE
Won't Get Fooled Again [The Who] - https://www.youtube.com/watch?v=SHhrZgojY1Q
Ace Of Spades [Motorhead] - https://www.youtube.com/watch?v=vcf7DnHi54g
The Game [Motorhead] - https://www.youtube.com/watch?v=F_JF8oSxXtM
Thunderstruck [AC/DC] - https://www.youtube.com/watch?v=v2AC41dglnM
Highway to Hell [AC/DC] - https://www.youtube.com/watch?v=l482T0yNkeo
Paranoid [Black Sabbath] - https://www.youtube.com/watch?v=uk_wUT1CvWM
Black Betty [Ram Jam] - https://www.youtube.com/watch?v=I_2D8Eo15wE
Alive [Pearl Jam] - https://www.youtube.com/watch?v=wGiTPgvKktM
Even Flow [Pearl Jam] - https://www.youtube.com/watch?v=tkbgtVFlyCQ

**Comment by Qaiten** [comment]
Another One Bites The Dust [Queen] -
https://youtu.be/JDaD2G9xjMc

Seven Nation Army [Glitch Mob] - 
https://youtu.be/GYFJjwXtsU4

Blue [Eiffel 65] -
https://youtu.be/zA52uNzx7Y4

**Comment by Saborknight** [comment]
We've got way too many song requests to be able to fit in an ACE interact menu. A solution needs to be found, and it may require either a dialogue or inventory "cassette tape" items per song. The former is probably the better idea, especially considering the music is synchronised between vehicles

**Comment by Saborknight** [comment]
### Other People's Song Requests
- [ ] Take Me Home, Country Roads [John Denver] - https://www.youtube.com/watch?v=1vrEljMfXYo
- [ ] Speedy Speedy Boy [Initial D] - https://www.youtube.com/watch?v=jPl_1RpBK_4
- [ ] Sympathy for the Devil [The Rolling Stones] - https://www.youtube.com/watch?v=GgnClrx8N2k
- [ ] Thunderstruck [AC/DC] - https://www.youtube.com/watch?v=v2AC41dglnM
- [ ] Battlefield 1942 Theme - https://www.youtube.com/watch?v=vg0Tmydj29M
- [ ] British Grenadiers - 8 bit - https://www.youtube.com/watch?v=GaRaztQQLQI

**Comment by Saborknight** [comment]
Done. Opening #44 to add missing functionality. Any additional song requests should follow the instructions here: https://github.com/Saborknight/2bnb-extras/wiki/Adding-New-Music

**Comment by Qaiten** [comment]
British Grenadiers - 8 bit - [https://www.youtube.com/watch?v=GaRaztQQLQI](url)
