### ISSUE TITLE
PIR Units who have had their guns shot out get another from their arse

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#47]
**Arma 3 Version:** `1.90` (stable)
**2BNB Extras Version:** `1.10.0` (stable)
**2BNB Modpack Version:** `2.0.0`

**Description:**
After an enemy unit goes into PIR wounded action, and looses his gun, if he gets back up he magically pulls another gun, same model, out of his arse.

**Steps to reproduce:**
- Shoot an AI down, not killing him
- Might need to shoot the gun out of their hands though
- Move over to that unit, wait until they get up again
- Watch them pull a gun out and nail your ass

**Where did the issue occur?**
- 2BNB Server

**Comment by UrekD** [comment]
They know the slav magic, I think  this might have been fixed in the PIR update which I'll update during the weekend

**Comment by Saborknight** [comment]
Hehe, alright

**Comment by UrekD** [comment]
Well PIR has been updated since then, any news?

**Comment by Saborknight** [comment]
Not sure, I'll keep an eye out.

**Comment by UrekD** [comment]
![20190609212923_1](https://user-images.githubusercontent.com/38784343/59163233-889fa180-8afe-11e9-90ab-dd8c44958296.jpg)
Saw this today
