### ISSUE TITLE
Survivable Crashes refusing to work on multiplayer server

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#53]
It just refuses to work. I thought this may have simple been because of the blunder made in 93b4eaa, but now having tested after removing that, I see it's still not working. Must have something to do with the error it keeps throwing: 

```sqf
22:45:17 Error in expression <vehType) then {
_isAllowed = true;
};
} forEach _vehKindWhitelist;
if (!(_isAllo>
22:45:17   Error position: <forEach _vehKindWhitelist;
if (!(_isAllo>
22:45:17   Error foreach: Type Bool, expected Array
22:45:17 File r0ed_SurvivableCrashes\functions\fn_vehicleInit.sqf, line 13
22:45:17 Error in expression <vehType) then {
_isAllowed = true;
};
} forEach _vehKindWhitelist;
if (!(_isAllo>
22:45:17   Error position: <forEach _vehKindWhitelist;
if (!(_isAllo>
22:45:17   Error Generic error in expression
22:45:17 File r0ed_SurvivableCrashes\functions\fn_vehicleInit.sqf, line 13
```

**Comment by Saborknight** [comment]
An here I find out the mod author has actually released a few fixes and stuff but not in the mod portion of his git repo, rather in some other bizarre location... so basically he has duplicate versions of the mod and has been developing on the one portion that hasn't been uploaded to steam workshop.......................

Updated location: https://github.com/Rafael09ED/Arma/tree/master/scripts/SurvivableCrashes.VR/r0ed_SurvivableCrashes
Out-of-date location: https://github.com/Rafael09ED/Arma/tree/master/mods/Survivable%20Crashes

so confused. Need sleep. Will work on it more tomorrow.

**Comment by Saborknight** [comment]
In terms of the error quoted in the initial comment, it doesn't seem to be caused by the stuf we're doing. Others have gotten it too: https://forums.bohemia.net/forums/topic/190516-survivable-crashes-shoot-downs-mod/?do=findComment&comment=3324506

**Comment by Saborknight** [comment]
https://github.com/Rafael09ED/Arma/issues/10#issuecomment-492033675

This explains a few things. Sounds like someone else needs to take the reigns on Survivable Crashes

**Comment by Saborknight** [comment]
This issue will now be moved to concern the repo https://github.com/Rafael09ED/Arma-Survivable-Crashes
All Survivable crashes related development will continue there.

**Comment by UrekD** [comment]
Most likely just gonna jerry rig it when we are done with desync for the time being 👍

**Comment by Saborknight** [comment]
Cool, in that case I'll leave this open for that then

**Comment by Saborknight** [comment]
Survivable crashes has been removed from modpack, so no jerry rigging today! When the mod has been fixed it will be re-added to the modpack, but not before
