### ISSUE TITLE
Set DUI "Classic" as the default but changeable option

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#55]
DUI has a new "Standard" option for the Squad Radar. This does not give a good sense of distance in a formation. So, make the "Classic" option appear as the default for the "Compass Style" option in the "DUI - Squad Radar - Radar" section.

**Comment by Saborknight** [comment]
> My only advice is then, make a patch mod which deletes the styles and readds them in the order you need.
> I wished it really would work with the cba settings... - Diwako

**Comment by UrekD** [comment]
For now we can just server force it, can't see anyone bitching about it really.

**Comment by Saborknight** [comment]
I don't see it being something as desperate as that. I think the only reason we need it is for the new guys so that they slowly get used to how far we're expecting their spacing to be.

In BCT I've been changing it with them manually every time anyway. As long as all the other BCT trainers uphold this, there shouldn't be too much of a problem. I don't want to restrict cosmetics like that.

**Comment by UrekD** [comment]
Do cba settings use a default value for list? If so can't we overwrite it? Then force classic via addon then stop it and everybody will have classic and other will be free to change back to their pref

**Comment by Saborknight** [comment]
Yeah, that's what Diwako ended up suggesting. We should just overwrite the Addon option, with a different default.

**Comment by Saborknight** [comment]
We've forced it to "Classical" server-side now, so this has become irrelevant.
