### ISSUE TITLE
Intel as an item which can be read using ace once picked up

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#60]
Idea is to have a items called Intel, Intel1... which zeus will be able to place and use them as objective. Once a soldier would find and pick up ex. Intel9, he would get an option while self interacting called Intel and in that group he would have an option called Read Intel9 and other's depending on the Intel he collected. Once selected a popup would open displaying the intel (possibly HTML formating for ease of use?), the info displayed should be defined either in the mission sqf or even cba setting.

TL:DR A book which you could read and would be used as intel, insted of the shitty diary entry system.

- [X] Working MP version just for reading without JIP support + Zeus module for placing it 
- [x] JIP
- [x] Destroy the Intel
- [ ] Proper diag for papers 
- [ ] Optimize code and do 0.1v Release
- [ ] Proper diag for computer + terminal
- [ ] Being able to pick papers up and transport on player
- [ ] Max carry of 5 papers
- [ ] dropping papers on death properly
- [ ] Being able to store papers in vehicles and boxes
- [ ] Puting digital intel to USB drive and reading it on remote 

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by UrekD** [comment]
Got the self interaction to work! Tho the ground model for the file is upright somehow 🤷‍♂ 
Now need to figure how to make a diag and sent text to it.

[SOmething to copy when I get back home](https://forums.bohemia.net/forums/topic/210288-inventoryobject-creation-mod/)

**Comment by UrekD** [comment]
![20190928201519_1](https://user-images.githubusercontent.com/38784343/65820784-78d2d700-e22d-11e9-9ebe-7572cde8e4cf.jpg)
![20190928201539_1](https://user-images.githubusercontent.com/38784343/65820785-78d2d700-e22d-11e9-9414-1520d18b41c8.jpg)

Working self interact, semi working CBA settings.

Need better items, since these have shitty rotation on dropped items, also a nicer UI but will do for now.

**Comment by UrekD** [comment]
![20190928202204_1](https://user-images.githubusercontent.com/38784343/65820799-aae43900-e22d-11e9-82a6-bd6114f63730.jpg)

**Comment by UrekD** [comment]
@Saborknight I commited if ya wish to look at the code b19925709da82a6f045b406636fdf47ba31cc2ba.

**Comment by Saborknight** [comment]
Nice, but next time you have something experimental, or WIP to commit, then make a new branch!
I've fixed your CBA Settings issue.
I have a suggestion though, why not use the Achilles Intel module, and hook into the object that creates. Then, override whatever script they use to add the intel to the diary with our own script that just adds the ACE interaction you have, and adds the item to the person's inventory?
That way, you don't have to do the models or Zeus modules, and you just handle the ACE Self-interaction and the intel display itself?

**Comment by UrekD** [comment]
Well my goal was to make intel physical instead of the diary thing, so you could only read it yourself not everyone on your side will get it added to the diary.

Also to make Intel objects readable and unreadable, so mission maker can say find and extract Docs folder that has x in em or Docs #715.

For now it should be mostly usable, I will make a nicer dialog and make a macro which should be more efficient in code, then look onto trying to make it so you can move n shit while having intel on your screen, also find some good item objects for docs, laptops n stuff. And that should be it for proper v.0.1.

I'd go kinda the way you said that it would script everything so yoh could do it on the go but, that eould need it's own framework for intel storage n shit, for that idk how and school again so no time, might look into that later.

**Comment by Saborknight** [comment]
So currently the Interaction points do show up on the item for all clients, after being on the server. They don't have JIP, so that needs to be done by me.

Also, the Zeus needs to be able to just write in the Title and Description and that's it. They shouldn't have to mess around with hypertext formatting. Just stick a title in one text field, and description in another.

Also, should have the display that pops up look like the object that's being displayed. Have a default set for any that aren't recognised though.

Also, when placing the module onto an object, it should apply the intel to that existing object. In this case, the default display should probably show.

That's my feedback anyway @GhostTheSlayer . Let me know if you need help with any parts of them.

**Comment by UrekD** [comment]
For picking up thing my idea is for item to tp to 0 0 0 and freeze, and when a player drops it/dies just tp it back to their position.

Or option 2. have the thing delete and save the text and shit to variables then create thing again and add actions etc...

What ya thing @Saborknight ?

**Comment by Saborknight** [comment]
The last thing you want is extra objects in a mission. Talk about performance killer. So yes, option 2.

**Comment by UrekD** [comment]
ACEX already does this https://github.com/acemod/ACEX/pull/11
@Saborknight I think youc an delete the other branch and close when you done.
