### ISSUE TITLE
Adjust vehicle inventories to our likings

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#62]
Change the default vehicle loadouts so that they carry the equipment we use and also extra resuply equipment such as extra mags,meds and AT, it's super simple easy for a beginer,

**Comment by Saborknight** [comment]
Since the removal of SMA, 04862cd has some broken items in the vehicle, such as the weapon in there, etc. These need to be fixed.

**Comment by Saborknight** [comment]
I'll be doing this in parallel with #61

**Comment by UrekD** [comment]
Vehicle needs their ammo REEEEEEEEEEE

**Comment by Saborknight** [comment]
All sorted in above commit

**Comment by UrekD** [comment]
Might wanna change thd stanag to MK318, 262 has the worst armor/barrier pen, designed for flesh mostly.

**Comment by Saborknight** [comment]
Good point, forgot about that

**Comment by Saborknight** [comment]
Done in the last commit
