### ISSUE TITLE
Error with cfgWeapons/SMA_Custom_HK416CustomVFG

### ISSUE THREAD

**Issue by Qaiten** [2bnb/2bnb-extras#71]
Upon entering a mission we have created;

Taking a regular slot in 1-Section (or any section besides Zeus), allows the mission to load with the titled error. However, when a Zeus loads into his slot, the map gets the error and won't load. 

Possibly due to vehicle loadouts, but it wouldn't explain why a Zeus wouldn't be able to load in, whereas a regular infantryman would.

**Comment by Saborknight** [comment]
#62 mentioned the vehicle inventory part. This issue is mainly about the Zeus slots breaking

**Comment by UrekD** [comment]
Isn't this fixed?

**Comment by Saborknight** [comment]
So, the SMA specific error yes, but not the second part to the issue:

> Taking a regular slot in 1-Section (or any section besides Zeus), allows the mission to load with the titled error. However, when a Zeus loads into his slot, the map gets the error and won't load.

@Qaiten has this continued to show up since?

**Comment by Saborknight** [comment]
@Qaiten confirms this isn't happening anymore.
