### ISSUE TITLE
Default Marksman load-out magazine error

### ISSUE THREAD

**Issue by Wolfpack2BNB** [2bnb/2bnb-extras#72]
**Arma 3 Version:** `1.xx` (stable / rc / dev)
**2BNB Extras Version:** `2.4.0` (stable / dev + commit hash)
**2BNB Modpack Version:** `2.2.0`

**Description:**
During little training, took a default marksman loadout, woodland cammo.
In the vest inventory, I had several 10rnd 7.62mm magazines that were not compatible with the default gun.
Might need to check the other default marksman load-outs as well for this error
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- 2BNB Server

**Comment by Saborknight** [comment]
Done in the last commit
