### ISSUE TITLE
Mission makers custom images - Where to put them

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#8]
Resources such as image's used to in game banners, signs, sounds etc. should from now on be defined in this addon.
So, when making a sign with Kompis's face on it, instead of needing to put the png in each mission and having the person download it, the mission should instead use the image from here and reduce the mission download time.

### To request new images for the mod
Create an issue [below](https://github.com/Saborknight/2bnb-extras/issues/new) and the technical team will get to adding it as quickly as possible!
Alternatively, contact either Ford or Arend on [Discord](https://discord.gg/DRaWNyf), and they will be able to add it for you.

**Comment by Saborknight** [comment]
@GhostTheSlayer mind making a wiki entry for this also?

**Comment by Saborknight** [comment]
Wiki entry created by @GhostTheSlayer , so I'm removing this issue from the project but leaving it open, so that it stays "Pinned".

**Comment by UrekD** [comment]
**You put images in :** 

> 2bnb-extras\addons\core\img

**call em like :**
`this setObjecttexture [0,"x\bnb_e\core\img\Norway.jpg"];`
