### ISSUE TITLE
Dependency bug 3CB FACTIONS

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#85]
![image](https://user-images.githubusercontent.com/38784343/69921592-9faec300-1493-11ea-92fe-8da2168d41b4.png)

**Comment by Saborknight** [comment]
Looks like it should just be a matter of inheriting from the RHS assets that 3CB was inheriting off in the first place anyway.

**Comment by Saborknight** [comment]
Done in the above commit. This will require a major version increment since it has changed some of the class names of vehicles!
