### ISSUE TITLE
Rework Terrarist faction

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#86]
Thing is broken, missing gear since SMA was removed etc.

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Saborknight** [comment]
Yep, @Qaiten likes it a lot though, so we should fix rather than remove from the mod.

**Comment by UrekD** [comment]
Fixed.
