### ISSUE TITLE
BNorway vehicles - Add explosive charge

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#98]
Add explosive charge to inventory in case vehicles need to be abandoned.

**Comment by Saborknight** [comment]
@Roa2879 how about we do this one together after the op tonight as an easy starter to get into it?

**Comment by Roa2879** [comment]
Would love to

ons. 25. mar. 2020 14.50 skrev Saborknight <notifications@github.com>:

**Comment by Saborknight** [comment]
Done in the below commit
